# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_LithoTool.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1239, 850)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(30, 17))
        self.label.setMaximumSize(QtCore.QSize(30, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(160, 17))
        self.dateTimeEdit.setMaximumSize(QtCore.QSize(160, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_4.addWidget(self.dateTimeEdit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(30, 17))
        self.label_2.setMaximumSize(QtCore.QSize(30, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit_2.setMinimumSize(QtCore.QSize(160, 17))
        self.dateTimeEdit_2.setMaximumSize(QtCore.QSize(160, 17))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dateTimeEdit_2.setFont(font)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.horizontalLayout_4.addWidget(self.dateTimeEdit_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4.setStretch(4, 100)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.scTable = QtWidgets.QTabWidget(self.centralwidget)
        self.scTable.setMinimumSize(QtCore.QSize(347, 250))
        self.scTable.setTabPosition(QtWidgets.QTabWidget.South)
        self.scTable.setObjectName("scTable")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setMinimumSize(QtCore.QSize(355, 135))
        self.groupBox_7.setMaximumSize(QtCore.QSize(355, 135))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.exLabel = QtWidgets.QLabel(self.groupBox_7)
        self.exLabel.setGeometry(QtCore.QRect(5, 10, 100, 16))
        self.exLabel.setMinimumSize(QtCore.QSize(100, 0))
        self.exLabel.setObjectName("exLabel")
        self.exLineEdit1_2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.exLineEdit1_2.setGeometry(QtCore.QRect(110, 10, 241, 20))
        self.exLineEdit1_2.setMinimumSize(QtCore.QSize(140, 0))
        self.exLineEdit1_2.setObjectName("exLineEdit1_2")
        self.exLabel_2 = QtWidgets.QLabel(self.groupBox_7)
        self.exLabel_2.setGeometry(QtCore.QRect(5, 32, 100, 16))
        self.exLabel_2.setMinimumSize(QtCore.QSize(100, 0))
        self.exLabel_2.setObjectName("exLabel_2")
        self.exRadioButton_3 = QtWidgets.QRadioButton(self.groupBox_7)
        self.exRadioButton_3.setGeometry(QtCore.QRect(130, 32, 140, 19))
        self.exRadioButton_3.setMinimumSize(QtCore.QSize(140, 0))
        self.exRadioButton_3.setObjectName("exRadioButton_3")
        self.exRadioButton_4 = QtWidgets.QRadioButton(self.groupBox_7)
        self.exRadioButton_4.setGeometry(QtCore.QRect(240, 32, 81, 19))
        self.exRadioButton_4.setMinimumSize(QtCore.QSize(0, 0))
        self.exRadioButton_4.setObjectName("exRadioButton_4")
        self.exLineEdit1_9 = QtWidgets.QLineEdit(self.groupBox_7)
        self.exLineEdit1_9.setGeometry(QtCore.QRect(56, 56, 61, 20))
        self.exLineEdit1_9.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_9.setObjectName("exLineEdit1_9")
        self.exLineEdit1_10 = QtWidgets.QLineEdit(self.groupBox_7)
        self.exLineEdit1_10.setGeometry(QtCore.QRect(134, 56, 61, 20))
        self.exLineEdit1_10.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_10.setObjectName("exLineEdit1_10")
        self.exLabel_3 = QtWidgets.QLabel(self.groupBox_7)
        self.exLabel_3.setGeometry(QtCore.QRect(7, 56, 100, 20))
        self.exLabel_3.setMinimumSize(QtCore.QSize(100, 20))
        self.exLabel_3.setMaximumSize(QtCore.QSize(105, 20))
        self.exLabel_3.setObjectName("exLabel_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setGeometry(QtCore.QRect(118, 56, 16, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.exComboBox = QtWidgets.QComboBox(self.groupBox_7)
        self.exComboBox.setGeometry(QtCore.QRect(7, 82, 81, 20))
        self.exComboBox.setObjectName("exComboBox")
        self.exComboBox_2 = QtWidgets.QComboBox(self.groupBox_7)
        self.exComboBox_2.setGeometry(QtCore.QRect(118, 82, 81, 20))
        self.exComboBox_2.setObjectName("exComboBox_2")
        self.exPushButton = QtWidgets.QPushButton(self.groupBox_7)
        self.exPushButton.setGeometry(QtCore.QRect(7, 108, 105, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exPushButton.sizePolicy().hasHeightForWidth())
        self.exPushButton.setSizePolicy(sizePolicy)
        self.exPushButton.setMinimumSize(QtCore.QSize(105, 20))
        self.exPushButton.setMaximumSize(QtCore.QSize(105, 20))
        self.exPushButton.setObjectName("exPushButton")
        self.exPushButton_2 = QtWidgets.QPushButton(self.groupBox_7)
        self.exPushButton_2.setGeometry(QtCore.QRect(118, 108, 105, 20))
        self.exPushButton_2.setMinimumSize(QtCore.QSize(105, 20))
        self.exPushButton_2.setMaximumSize(QtCore.QSize(105, 20))
        self.exPushButton_2.setObjectName("exPushButton_2")
        self.exLabel_4 = QtWidgets.QLabel(self.groupBox_7)
        self.exLabel_4.setGeometry(QtCore.QRect(244, 56, 100, 20))
        self.exLabel_4.setMinimumSize(QtCore.QSize(100, 20))
        self.exLabel_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.exLabel_4.setObjectName("exLabel_4")
        self.exPushButton_3 = QtWidgets.QPushButton(self.groupBox_7)
        self.exPushButton_3.setGeometry(QtCore.QRect(244, 82, 105, 20))
        self.exPushButton_3.setMinimumSize(QtCore.QSize(105, 20))
        self.exPushButton_3.setMaximumSize(QtCore.QSize(105, 20))
        self.exPushButton_3.setObjectName("exPushButton_3")
        self.exPushButton_4 = QtWidgets.QPushButton(self.groupBox_7)
        self.exPushButton_4.setGeometry(QtCore.QRect(244, 108, 105, 20))
        self.exPushButton_4.setMinimumSize(QtCore.QSize(105, 20))
        self.exPushButton_4.setMaximumSize(QtCore.QSize(105, 20))
        self.exPushButton_4.setObjectName("exPushButton_4")
        self.horizontalLayout_38.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setMinimumSize(QtCore.QSize(210, 135))
        self.groupBox_8.setMaximumSize(QtCore.QSize(355, 135))
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.exLineEdit1_12 = QtWidgets.QLineEdit(self.groupBox_8)
        self.exLineEdit1_12.setGeometry(QtCore.QRect(2, 10, 95, 20))
        self.exLineEdit1_12.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_12.setObjectName("exLineEdit1_12")
        self.label_4 = QtWidgets.QLabel(self.groupBox_8)
        self.label_4.setGeometry(QtCore.QRect(118, 56, 16, 16))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.exLineEdit1_13 = QtWidgets.QLineEdit(self.groupBox_8)
        self.exLineEdit1_13.setGeometry(QtCore.QRect(110, 10, 95, 20))
        self.exLineEdit1_13.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_13.setObjectName("exLineEdit1_13")
        self.exLineEdit1_14 = QtWidgets.QLineEdit(self.groupBox_8)
        self.exLineEdit1_14.setGeometry(QtCore.QRect(110, 40, 95, 20))
        self.exLineEdit1_14.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_14.setObjectName("exLineEdit1_14")
        self.exLineEdit1_29 = QtWidgets.QLineEdit(self.groupBox_8)
        self.exLineEdit1_29.setGeometry(QtCore.QRect(2, 40, 95, 20))
        self.exLineEdit1_29.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_29.setObjectName("exLineEdit1_29")
        self.exLineEdit1_30 = QtWidgets.QLineEdit(self.groupBox_8)
        self.exLineEdit1_30.setGeometry(QtCore.QRect(110, 70, 95, 20))
        self.exLineEdit1_30.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_30.setObjectName("exLineEdit1_30")
        self.exLineEdit1_31 = QtWidgets.QLineEdit(self.groupBox_8)
        self.exLineEdit1_31.setGeometry(QtCore.QRect(2, 70, 95, 20))
        self.exLineEdit1_31.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_31.setObjectName("exLineEdit1_31")
        self.exLineEdit1_32 = QtWidgets.QLineEdit(self.groupBox_8)
        self.exLineEdit1_32.setGeometry(QtCore.QRect(0, 100, 95, 20))
        self.exLineEdit1_32.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_32.setObjectName("exLineEdit1_32")
        self.exLineEdit1_33 = QtWidgets.QLineEdit(self.groupBox_8)
        self.exLineEdit1_33.setGeometry(QtCore.QRect(108, 100, 95, 20))
        self.exLineEdit1_33.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_33.setObjectName("exLineEdit1_33")
        self.horizontalLayout_38.addWidget(self.groupBox_8)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.groupBox_33 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_33.setMinimumSize(QtCore.QSize(585, 50))
        self.groupBox_33.setMaximumSize(QtCore.QSize(585, 81))
        self.groupBox_33.setTitle("")
        self.groupBox_33.setObjectName("groupBox_33")
        self.exLineEdit1_34 = QtWidgets.QLineEdit(self.groupBox_33)
        self.exLineEdit1_34.setGeometry(QtCore.QRect(372, 59, 127, 20))
        self.exLineEdit1_34.setMinimumSize(QtCore.QSize(100, 0))
        self.exLineEdit1_34.setObjectName("exLineEdit1_34")
        self.exLineEdit1_35 = QtWidgets.QLineEdit(self.groupBox_33)
        self.exLineEdit1_35.setGeometry(QtCore.QRect(92, 59, 127, 20))
        self.exLineEdit1_35.setMinimumSize(QtCore.QSize(100, 0))
        self.exLineEdit1_35.setObjectName("exLineEdit1_35")
        self.exLabel_23 = QtWidgets.QLabel(self.groupBox_33)
        self.exLabel_23.setGeometry(QtCore.QRect(323, 59, 41, 16))
        self.exLabel_23.setMinimumSize(QtCore.QSize(0, 0))
        self.exLabel_23.setObjectName("exLabel_23")
        self.exLineEdit1_55 = QtWidgets.QLineEdit(self.groupBox_33)
        self.exLineEdit1_55.setGeometry(QtCore.QRect(2, 5, 110, 20))
        self.exLineEdit1_55.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_55.setObjectName("exLineEdit1_55")
        self.exLineEdit1_56 = QtWidgets.QLineEdit(self.groupBox_33)
        self.exLineEdit1_56.setGeometry(QtCore.QRect(115, 5, 110, 20))
        self.exLineEdit1_56.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_56.setObjectName("exLineEdit1_56")
        self.exLineEdit1_57 = QtWidgets.QLineEdit(self.groupBox_33)
        self.exLineEdit1_57.setGeometry(QtCore.QRect(-107, 10, 95, 20))
        self.exLineEdit1_57.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_57.setObjectName("exLineEdit1_57")
        self.exLineEdit1_80 = QtWidgets.QLineEdit(self.groupBox_33)
        self.exLineEdit1_80.setGeometry(QtCore.QRect(2, 28, 110, 20))
        self.exLineEdit1_80.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_80.setObjectName("exLineEdit1_80")
        self.exLineEdit1_81 = QtWidgets.QLineEdit(self.groupBox_33)
        self.exLineEdit1_81.setGeometry(QtCore.QRect(115, 28, 110, 20))
        self.exLineEdit1_81.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_81.setObjectName("exLineEdit1_81")
        self.exPushButton_25 = QtWidgets.QPushButton(self.groupBox_33)
        self.exPushButton_25.setGeometry(QtCore.QRect(236, 10, 75, 30))
        self.exPushButton_25.setMinimumSize(QtCore.QSize(50, 20))
        self.exPushButton_25.setMaximumSize(QtCore.QSize(9999, 99999))
        self.exPushButton_25.setObjectName("exPushButton_25")
        self.exPushButton_26 = QtWidgets.QPushButton(self.groupBox_33)
        self.exPushButton_26.setGeometry(QtCore.QRect(320, 10, 75, 30))
        self.exPushButton_26.setMinimumSize(QtCore.QSize(50, 20))
        self.exPushButton_26.setMaximumSize(QtCore.QSize(9999, 99999))
        self.exPushButton_26.setObjectName("exPushButton_26")
        self.exLineEdit1_82 = QtWidgets.QLineEdit(self.groupBox_33)
        self.exLineEdit1_82.setGeometry(QtCore.QRect(400, 28, 110, 20))
        self.exLineEdit1_82.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_82.setObjectName("exLineEdit1_82")
        self.exLineEdit1_83 = QtWidgets.QLineEdit(self.groupBox_33)
        self.exLineEdit1_83.setGeometry(QtCore.QRect(400, 5, 110, 20))
        self.exLineEdit1_83.setMinimumSize(QtCore.QSize(0, 0))
        self.exLineEdit1_83.setObjectName("exLineEdit1_83")
        self.exPushButton_27 = QtWidgets.QPushButton(self.groupBox_33)
        self.exPushButton_27.setGeometry(QtCore.QRect(517, 10, 61, 30))
        self.exPushButton_27.setMinimumSize(QtCore.QSize(50, 20))
        self.exPushButton_27.setMaximumSize(QtCore.QSize(9999, 99999))
        self.exPushButton_27.setObjectName("exPushButton_27")
        self.verticalLayout_22.addWidget(self.groupBox_33)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setMinimumSize(QtCore.QSize(585, 81))
        self.groupBox_9.setMaximumSize(QtCore.QSize(585, 81))
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.exLineEdit1_7 = QtWidgets.QLineEdit(self.groupBox_9)
        self.exLineEdit1_7.setGeometry(QtCore.QRect(372, 59, 127, 20))
        self.exLineEdit1_7.setMinimumSize(QtCore.QSize(100, 0))
        self.exLineEdit1_7.setObjectName("exLineEdit1_7")
        self.exPushButton_10 = QtWidgets.QPushButton(self.groupBox_9)
        self.exPushButton_10.setGeometry(QtCore.QRect(504, 46, 75, 31))
        self.exPushButton_10.setMinimumSize(QtCore.QSize(50, 20))
        self.exPushButton_10.setMaximumSize(QtCore.QSize(9999, 99999))
        self.exPushButton_10.setObjectName("exPushButton_10")
        self.exLabel_7 = QtWidgets.QLabel(self.groupBox_9)
        self.exLabel_7.setGeometry(QtCore.QRect(3, 59, 88, 16))
        self.exLabel_7.setMinimumSize(QtCore.QSize(88, 0))
        self.exLabel_7.setObjectName("exLabel_7")
        self.exPushButton_9 = QtWidgets.QPushButton(self.groupBox_9)
        self.exPushButton_9.setGeometry(QtCore.QRect(504, 7, 75, 31))
        self.exPushButton_9.setMinimumSize(QtCore.QSize(50, 20))
        self.exPushButton_9.setMaximumSize(QtCore.QSize(9999, 99999))
        self.exPushButton_9.setText("")
        self.exPushButton_9.setObjectName("exPushButton_9")
        self.exLineEdit1_5 = QtWidgets.QLineEdit(self.groupBox_9)
        self.exLineEdit1_5.setGeometry(QtCore.QRect(92, 59, 127, 20))
        self.exLineEdit1_5.setMinimumSize(QtCore.QSize(100, 0))
        self.exLineEdit1_5.setObjectName("exLineEdit1_5")
        self.exLineEdit1_8 = QtWidgets.QLineEdit(self.groupBox_9)
        self.exLineEdit1_8.setGeometry(QtCore.QRect(372, 7, 127, 20))
        self.exLineEdit1_8.setMinimumSize(QtCore.QSize(100, 0))
        self.exLineEdit1_8.setObjectName("exLineEdit1_8")
        self.exLabel_5 = QtWidgets.QLabel(self.groupBox_9)
        self.exLabel_5.setGeometry(QtCore.QRect(3, 7, 80, 20))
        self.exLabel_5.setMinimumSize(QtCore.QSize(80, 0))
        self.exLabel_5.setObjectName("exLabel_5")
        self.exLabel_8 = QtWidgets.QLabel(self.groupBox_9)
        self.exLabel_8.setGeometry(QtCore.QRect(323, 59, 41, 16))
        self.exLabel_8.setMinimumSize(QtCore.QSize(0, 0))
        self.exLabel_8.setObjectName("exLabel_8")
        self.exLineEdit1_6 = QtWidgets.QLineEdit(self.groupBox_9)
        self.exLineEdit1_6.setGeometry(QtCore.QRect(372, 33, 127, 20))
        self.exLineEdit1_6.setMinimumSize(QtCore.QSize(100, 0))
        self.exLineEdit1_6.setObjectName("exLineEdit1_6")
        self.exLabel_6 = QtWidgets.QLabel(self.groupBox_9)
        self.exLabel_6.setGeometry(QtCore.QRect(3, 33, 80, 16))
        self.exLabel_6.setMinimumSize(QtCore.QSize(80, 0))
        self.exLabel_6.setObjectName("exLabel_6")
        self.exPushButton_88 = QtWidgets.QPushButton(self.groupBox_9)
        self.exPushButton_88.setGeometry(QtCore.QRect(225, 7, 75, 71))
        self.exPushButton_88.setMinimumSize(QtCore.QSize(50, 20))
        self.exPushButton_88.setMaximumSize(QtCore.QSize(9999, 99999))
        self.exPushButton_88.setObjectName("exPushButton_88")
        self.exLabel_9 = QtWidgets.QLabel(self.groupBox_9)
        self.exLabel_9.setGeometry(QtCore.QRect(323, 7, 41, 16))
        self.exLabel_9.setMinimumSize(QtCore.QSize(0, 0))
        self.exLabel_9.setObjectName("exLabel_9")
        self.exLineEdit1_3 = QtWidgets.QLineEdit(self.groupBox_9)
        self.exLineEdit1_3.setGeometry(QtCore.QRect(92, 7, 127, 20))
        self.exLineEdit1_3.setMinimumSize(QtCore.QSize(100, 0))
        self.exLineEdit1_3.setObjectName("exLineEdit1_3")
        self.exLabel_10 = QtWidgets.QLabel(self.groupBox_9)
        self.exLabel_10.setGeometry(QtCore.QRect(323, 33, 41, 16))
        self.exLabel_10.setMinimumSize(QtCore.QSize(0, 0))
        self.exLabel_10.setObjectName("exLabel_10")
        self.exLineEdit1_4 = QtWidgets.QLineEdit(self.groupBox_9)
        self.exLineEdit1_4.setGeometry(QtCore.QRect(92, 33, 127, 20))
        self.exLineEdit1_4.setMinimumSize(QtCore.QSize(100, 0))
        self.exLineEdit1_4.setObjectName("exLineEdit1_4")
        self.verticalLayout_22.addWidget(self.groupBox_9)
        self.horizontalLayout_38.addLayout(self.verticalLayout_22)
        spacerItem1 = QtWidgets.QSpacerItem(9, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_38)
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_15.setMinimumSize(QtCore.QSize(888, 50))
        self.groupBox_15.setTitle("")
        self.groupBox_15.setObjectName("groupBox_15")
        self.exPushButton_28 = QtWidgets.QPushButton(self.groupBox_15)
        self.exPushButton_28.setGeometry(QtCore.QRect(10, 10, 91, 30))
        self.exPushButton_28.setMinimumSize(QtCore.QSize(50, 30))
        self.exPushButton_28.setMaximumSize(QtCore.QSize(9999, 99999))
        self.exPushButton_28.setObjectName("exPushButton_28")
        self.exPushButton_29 = QtWidgets.QPushButton(self.groupBox_15)
        self.exPushButton_29.setGeometry(QtCore.QRect(120, 10, 91, 30))
        self.exPushButton_29.setMinimumSize(QtCore.QSize(50, 30))
        self.exPushButton_29.setMaximumSize(QtCore.QSize(9999, 99999))
        self.exPushButton_29.setObjectName("exPushButton_29")
        self.exPushButton_30 = QtWidgets.QPushButton(self.groupBox_15)
        self.exPushButton_30.setGeometry(QtCore.QRect(230, 10, 91, 30))
        self.exPushButton_30.setMinimumSize(QtCore.QSize(50, 30))
        self.exPushButton_30.setMaximumSize(QtCore.QSize(9999, 99999))
        self.exPushButton_30.setObjectName("exPushButton_30")
        self.exPushButton_31 = QtWidgets.QPushButton(self.groupBox_15)
        self.exPushButton_31.setGeometry(QtCore.QRect(334, 10, 91, 30))
        self.exPushButton_31.setMinimumSize(QtCore.QSize(50, 30))
        self.exPushButton_31.setMaximumSize(QtCore.QSize(9999, 99999))
        self.exPushButton_31.setObjectName("exPushButton_31")
        self.verticalLayout_3.addWidget(self.groupBox_15)
        self.exTable = QtWidgets.QTableWidget(self.tab)
        self.exTable.setObjectName("exTable")
        self.exTable.setColumnCount(0)
        self.exTable.setRowCount(0)
        self.verticalLayout_3.addWidget(self.exTable)
        self.scTable.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_12.setMinimumSize(QtCore.QSize(1000, 60))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.scBtn01 = QtWidgets.QPushButton(self.groupBox_12)
        self.scBtn01.setGeometry(QtCore.QRect(6, 2, 75, 24))
        self.scBtn01.setMinimumSize(QtCore.QSize(75, 0))
        self.scBtn01.setObjectName("scBtn01")
        self.scBtn02 = QtWidgets.QPushButton(self.groupBox_12)
        self.scBtn02.setGeometry(QtCore.QRect(87, 2, 75, 24))
        self.scBtn02.setMinimumSize(QtCore.QSize(75, 0))
        self.scBtn02.setObjectName("scBtn02")
        self.scBtn03 = QtWidgets.QPushButton(self.groupBox_12)
        self.scBtn03.setGeometry(QtCore.QRect(168, 2, 75, 24))
        self.scBtn03.setMinimumSize(QtCore.QSize(75, 0))
        self.scBtn03.setObjectName("scBtn03")
        self.scBtn04 = QtWidgets.QPushButton(self.groupBox_12)
        self.scBtn04.setGeometry(QtCore.QRect(249, 2, 75, 24))
        self.scBtn04.setMinimumSize(QtCore.QSize(75, 0))
        self.scBtn04.setObjectName("scBtn04")
        self.scBtn05 = QtWidgets.QPushButton(self.groupBox_12)
        self.scBtn05.setGeometry(QtCore.QRect(330, 2, 75, 24))
        self.scBtn05.setMinimumSize(QtCore.QSize(75, 0))
        self.scBtn05.setObjectName("scBtn05")
        self.scBtn06 = QtWidgets.QPushButton(self.groupBox_12)
        self.scBtn06.setGeometry(QtCore.QRect(411, 2, 75, 24))
        self.scBtn06.setMinimumSize(QtCore.QSize(75, 0))
        self.scBtn06.setObjectName("scBtn06")
        self.scBtn07 = QtWidgets.QPushButton(self.groupBox_12)
        self.scBtn07.setGeometry(QtCore.QRect(492, 2, 75, 24))
        self.scBtn07.setMinimumSize(QtCore.QSize(75, 0))
        self.scBtn07.setObjectName("scBtn07")
        self.scBtn08 = QtWidgets.QPushButton(self.groupBox_12)
        self.scBtn08.setGeometry(QtCore.QRect(573, 2, 75, 24))
        self.scBtn08.setMinimumSize(QtCore.QSize(75, 0))
        self.scBtn08.setObjectName("scBtn08")
        self.scBtn09 = QtWidgets.QPushButton(self.groupBox_12)
        self.scBtn09.setGeometry(QtCore.QRect(654, 2, 75, 24))
        self.scBtn09.setMinimumSize(QtCore.QSize(75, 0))
        self.scBtn09.setObjectName("scBtn09")
        self.scBtn10 = QtWidgets.QPushButton(self.groupBox_12)
        self.scBtn10.setGeometry(QtCore.QRect(735, 2, 75, 24))
        self.scBtn10.setMinimumSize(QtCore.QSize(75, 0))
        self.scBtn10.setObjectName("scBtn10")
        self.scBtn11 = QtWidgets.QPushButton(self.groupBox_12)
        self.scBtn11.setGeometry(QtCore.QRect(816, 2, 75, 24))
        self.scBtn11.setMinimumSize(QtCore.QSize(75, 0))
        self.scBtn11.setObjectName("scBtn11")
        self.verticalLayout_4.addWidget(self.groupBox_12)
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_14.setMinimumSize(QtCore.QSize(1000, 60))
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.scBtn30 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn30.setGeometry(QtCore.QRect(5, 2, 80, 24))
        self.scBtn30.setObjectName("scBtn30")
        self.scBtn31 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn31.setGeometry(QtCore.QRect(89, 2, 80, 24))
        self.scBtn31.setObjectName("scBtn31")
        self.scBtn32 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn32.setGeometry(QtCore.QRect(173, 2, 80, 24))
        self.scBtn32.setObjectName("scBtn32")
        self.scBtn33 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn33.setGeometry(QtCore.QRect(257, 2, 80, 24))
        self.scBtn33.setObjectName("scBtn33")
        self.scBtn34 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn34.setGeometry(QtCore.QRect(341, 2, 80, 24))
        self.scBtn34.setObjectName("scBtn34")
        self.scBtn35 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn35.setGeometry(QtCore.QRect(425, 2, 80, 24))
        self.scBtn35.setObjectName("scBtn35")
        self.scBtn36 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn36.setGeometry(QtCore.QRect(510, 2, 80, 24))
        self.scBtn36.setObjectName("scBtn36")
        self.scBtn37 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn37.setGeometry(QtCore.QRect(595, 2, 80, 24))
        self.scBtn37.setObjectName("scBtn37")
        self.scBtn38 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn38.setGeometry(QtCore.QRect(679, 2, 80, 24))
        self.scBtn38.setObjectName("scBtn38")
        self.scBtn39 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn39.setGeometry(QtCore.QRect(763, 2, 80, 24))
        self.scBtn39.setObjectName("scBtn39")
        self.scBtn40 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn40.setGeometry(QtCore.QRect(847, 2, 80, 24))
        self.scBtn40.setObjectName("scBtn40")
        self.scBtn41 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn41.setGeometry(QtCore.QRect(5, 34, 80, 24))
        self.scBtn41.setObjectName("scBtn41")
        self.scBtn51 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn51.setGeometry(QtCore.QRect(847, 34, 80, 24))
        self.scBtn51.setObjectName("scBtn51")
        self.scBtn47 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn47.setGeometry(QtCore.QRect(510, 34, 80, 24))
        self.scBtn47.setObjectName("scBtn47")
        self.scBtn44 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn44.setGeometry(QtCore.QRect(257, 34, 80, 24))
        self.scBtn44.setObjectName("scBtn44")
        self.scBtn49 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn49.setGeometry(QtCore.QRect(679, 34, 80, 24))
        self.scBtn49.setObjectName("scBtn49")
        self.scBtn43 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn43.setGeometry(QtCore.QRect(173, 34, 80, 24))
        self.scBtn43.setObjectName("scBtn43")
        self.scBtn42 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn42.setGeometry(QtCore.QRect(89, 34, 80, 24))
        self.scBtn42.setObjectName("scBtn42")
        self.scBtn48 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn48.setGeometry(QtCore.QRect(595, 34, 80, 24))
        self.scBtn48.setObjectName("scBtn48")
        self.scBtn46 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn46.setGeometry(QtCore.QRect(425, 34, 80, 24))
        self.scBtn46.setObjectName("scBtn46")
        self.scBtn45 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn45.setGeometry(QtCore.QRect(341, 34, 80, 24))
        self.scBtn45.setObjectName("scBtn45")
        self.scBtn50 = QtWidgets.QPushButton(self.groupBox_14)
        self.scBtn50.setGeometry(QtCore.QRect(763, 34, 80, 24))
        self.scBtn50.setObjectName("scBtn50")
        self.verticalLayout_4.addWidget(self.groupBox_14)
        self.scTab = QtWidgets.QTableWidget(self.tab_2)
        self.scTab.setObjectName("scTab")
        self.scTab.setColumnCount(0)
        self.scTab.setRowCount(0)
        self.verticalLayout_4.addWidget(self.scTab)
        self.scTable.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_2.setMinimumSize(QtCore.QSize(1155, 50))
        self.groupBox_2.setMaximumSize(QtCore.QSize(1155, 50))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 891, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.r2rRadioBtn01 = QtWidgets.QRadioButton(self.layoutWidget)
        self.r2rRadioBtn01.setObjectName("r2rRadioBtn01")
        self.horizontalLayout_6.addWidget(self.r2rRadioBtn01)
        self.r2rRadioBtn02 = QtWidgets.QRadioButton(self.layoutWidget)
        self.r2rRadioBtn02.setObjectName("r2rRadioBtn02")
        self.horizontalLayout_6.addWidget(self.r2rRadioBtn02)
        self.r2rBtn01 = QtWidgets.QPushButton(self.layoutWidget)
        self.r2rBtn01.setMinimumSize(QtCore.QSize(50, 24))
        self.r2rBtn01.setMaximumSize(QtCore.QSize(50, 24))
        self.r2rBtn01.setObjectName("r2rBtn01")
        self.horizontalLayout_6.addWidget(self.r2rBtn01)
        self.r2rBtn02 = QtWidgets.QPushButton(self.layoutWidget)
        self.r2rBtn02.setMinimumSize(QtCore.QSize(50, 24))
        self.r2rBtn02.setMaximumSize(QtCore.QSize(50, 24))
        self.r2rBtn02.setObjectName("r2rBtn02")
        self.horizontalLayout_6.addWidget(self.r2rBtn02)
        self.r2rBtn03 = QtWidgets.QPushButton(self.layoutWidget)
        self.r2rBtn03.setMinimumSize(QtCore.QSize(50, 24))
        self.r2rBtn03.setMaximumSize(QtCore.QSize(50, 24))
        self.r2rBtn03.setObjectName("r2rBtn03")
        self.horizontalLayout_6.addWidget(self.r2rBtn03)
        self.r2rLineEdit01 = QtWidgets.QLineEdit(self.layoutWidget)
        self.r2rLineEdit01.setMinimumSize(QtCore.QSize(80, 24))
        self.r2rLineEdit01.setObjectName("r2rLineEdit01")
        self.horizontalLayout_6.addWidget(self.r2rLineEdit01)
        self.r2rLineEdit02 = QtWidgets.QLineEdit(self.layoutWidget)
        self.r2rLineEdit02.setMinimumSize(QtCore.QSize(80, 24))
        self.r2rLineEdit02.setObjectName("r2rLineEdit02")
        self.horizontalLayout_6.addWidget(self.r2rLineEdit02)
        self.r2rLineEdit03 = QtWidgets.QLineEdit(self.layoutWidget)
        self.r2rLineEdit03.setMinimumSize(QtCore.QSize(80, 24))
        self.r2rLineEdit03.setObjectName("r2rLineEdit03")
        self.horizontalLayout_6.addWidget(self.r2rLineEdit03)
        self.r2rLineEdit04 = QtWidgets.QLineEdit(self.layoutWidget)
        self.r2rLineEdit04.setMinimumSize(QtCore.QSize(80, 24))
        self.r2rLineEdit04.setObjectName("r2rLineEdit04")
        self.horizontalLayout_6.addWidget(self.r2rLineEdit04)
        self.r2rBtn04 = QtWidgets.QPushButton(self.layoutWidget)
        self.r2rBtn04.setMinimumSize(QtCore.QSize(50, 24))
        self.r2rBtn04.setMaximumSize(QtCore.QSize(50, 24))
        self.r2rBtn04.setObjectName("r2rBtn04")
        self.horizontalLayout_6.addWidget(self.r2rBtn04)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setMinimumSize(QtCore.QSize(1155, 111))
        self.groupBox_4.setMaximumSize(QtCore.QSize(1155, 111))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.r2rBtnFilter = QtWidgets.QPushButton(self.groupBox_4)
        self.r2rBtnFilter.setGeometry(QtCore.QRect(797, 20, 70, 70))
        self.r2rBtnFilter.setMinimumSize(QtCore.QSize(70, 70))
        self.r2rBtnFilter.setMaximumSize(QtCore.QSize(0, 0))
        self.r2rBtnFilter.setObjectName("r2rBtnFilter")
        self.r2rListTech = QtWidgets.QListWidget(self.groupBox_4)
        self.r2rListTech.setGeometry(QtCore.QRect(11, 10, 131, 91))
        self.r2rListTech.setMinimumSize(QtCore.QSize(0, 70))
        self.r2rListTech.setMaximumSize(QtCore.QSize(140, 1000))
        self.r2rListTech.setObjectName("r2rListTech")
        self.r2rListLayer = QtWidgets.QListWidget(self.groupBox_4)
        self.r2rListLayer.setGeometry(QtCore.QRect(303, 10, 131, 91))
        self.r2rListLayer.setMinimumSize(QtCore.QSize(0, 70))
        self.r2rListLayer.setMaximumSize(QtCore.QSize(140, 1000))
        self.r2rListLayer.setObjectName("r2rListLayer")
        self.r2rListPart = QtWidgets.QListWidget(self.groupBox_4)
        self.r2rListPart.setGeometry(QtCore.QRect(157, 10, 131, 91))
        self.r2rListPart.setMinimumSize(QtCore.QSize(0, 70))
        self.r2rListPart.setMaximumSize(QtCore.QSize(140, 1000))
        self.r2rListPart.setObjectName("r2rListPart")
        self.r2rListDate = QtWidgets.QListWidget(self.groupBox_4)
        self.r2rListDate.setGeometry(QtCore.QRect(595, 10, 191, 91))
        self.r2rListDate.setMinimumSize(QtCore.QSize(0, 70))
        self.r2rListDate.setMaximumSize(QtCore.QSize(200, 1000))
        self.r2rListDate.setObjectName("r2rListDate")
        self.r2rListTool = QtWidgets.QListWidget(self.groupBox_4)
        self.r2rListTool.setGeometry(QtCore.QRect(449, 10, 131, 91))
        self.r2rListTool.setMinimumSize(QtCore.QSize(0, 70))
        self.r2rListTool.setMaximumSize(QtCore.QSize(140, 1000))
        self.r2rListTool.setObjectName("r2rListTool")
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox.setMinimumSize(QtCore.QSize(1155, 41))
        self.groupBox.setMaximumSize(QtCore.QSize(1155, 41))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(640, 6, 164, 32))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.r2rBtnByDate = QtWidgets.QPushButton(self.layoutWidget1)
        self.r2rBtnByDate.setMinimumSize(QtCore.QSize(50, 30))
        self.r2rBtnByDate.setMaximumSize(QtCore.QSize(50, 30))
        self.r2rBtnByDate.setObjectName("r2rBtnByDate")
        self.horizontalLayout.addWidget(self.r2rBtnByDate)
        self.r2rBtnByTool = QtWidgets.QPushButton(self.layoutWidget1)
        self.r2rBtnByTool.setMinimumSize(QtCore.QSize(50, 30))
        self.r2rBtnByTool.setMaximumSize(QtCore.QSize(50, 30))
        self.r2rBtnByTool.setObjectName("r2rBtnByTool")
        self.horizontalLayout.addWidget(self.r2rBtnByTool)
        self.r2rBtnByPart = QtWidgets.QPushButton(self.layoutWidget1)
        self.r2rBtnByPart.setMinimumSize(QtCore.QSize(50, 30))
        self.r2rBtnByPart.setMaximumSize(QtCore.QSize(50, 30))
        self.r2rBtnByPart.setObjectName("r2rBtnByPart")
        self.horizontalLayout.addWidget(self.r2rBtnByPart)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 13, 609, 21))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.r2rRadioTranX = QtWidgets.QRadioButton(self.layoutWidget2)
        self.r2rRadioTranX.setObjectName("r2rRadioTranX")
        self.horizontalLayout_8.addWidget(self.r2rRadioTranX)
        self.r2rRadioTranY = QtWidgets.QRadioButton(self.layoutWidget2)
        self.r2rRadioTranY.setObjectName("r2rRadioTranY")
        self.horizontalLayout_8.addWidget(self.r2rRadioTranY)
        self.r2rRadioExpX = QtWidgets.QRadioButton(self.layoutWidget2)
        self.r2rRadioExpX.setObjectName("r2rRadioExpX")
        self.horizontalLayout_8.addWidget(self.r2rRadioExpX)
        self.r2rRadioExpY = QtWidgets.QRadioButton(self.layoutWidget2)
        self.r2rRadioExpY.setObjectName("r2rRadioExpY")
        self.horizontalLayout_8.addWidget(self.r2rRadioExpY)
        self.r2rRadioOrt = QtWidgets.QRadioButton(self.layoutWidget2)
        self.r2rRadioOrt.setObjectName("r2rRadioOrt")
        self.horizontalLayout_8.addWidget(self.r2rRadioOrt)
        self.r2rRadioRot = QtWidgets.QRadioButton(self.layoutWidget2)
        self.r2rRadioRot.setObjectName("r2rRadioRot")
        self.horizontalLayout_8.addWidget(self.r2rRadioRot)
        self.r2rRadioSMag = QtWidgets.QRadioButton(self.layoutWidget2)
        self.r2rRadioSMag.setObjectName("r2rRadioSMag")
        self.horizontalLayout_8.addWidget(self.r2rRadioSMag)
        self.r2rRadioSRot = QtWidgets.QRadioButton(self.layoutWidget2)
        self.r2rRadioSRot.setObjectName("r2rRadioSRot")
        self.horizontalLayout_8.addWidget(self.r2rRadioSRot)
        self.r2rRadioAMag = QtWidgets.QRadioButton(self.layoutWidget2)
        self.r2rRadioAMag.setObjectName("r2rRadioAMag")
        self.horizontalLayout_8.addWidget(self.r2rRadioAMag)
        self.r2rRadioARot = QtWidgets.QRadioButton(self.layoutWidget2)
        self.r2rRadioARot.setObjectName("r2rRadioARot")
        self.horizontalLayout_8.addWidget(self.r2rRadioARot)
        self.r2rRadioCD = QtWidgets.QRadioButton(self.layoutWidget2)
        self.r2rRadioCD.setObjectName("r2rRadioCD")
        self.horizontalLayout_8.addWidget(self.r2rRadioCD)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setMinimumSize(QtCore.QSize(1155, 71))
        self.groupBox_3.setMaximumSize(QtCore.QSize(1155, 71))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 580, 52))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.r2rListLayer1 = QtWidgets.QListWidget(self.layoutWidget3)
        self.r2rListLayer1.setMinimumSize(QtCore.QSize(0, 30))
        self.r2rListLayer1.setMaximumSize(QtCore.QSize(140, 50))
        self.r2rListLayer1.setObjectName("r2rListLayer1")
        self.horizontalLayout_3.addWidget(self.r2rListLayer1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.r2rListLayer2 = QtWidgets.QListWidget(self.layoutWidget3)
        self.r2rListLayer2.setMinimumSize(QtCore.QSize(0, 30))
        self.r2rListLayer2.setMaximumSize(QtCore.QSize(140, 50))
        self.r2rListLayer2.setObjectName("r2rListLayer2")
        self.horizontalLayout_3.addWidget(self.r2rListLayer2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.r2RLineX = QtWidgets.QLineEdit(self.layoutWidget3)
        self.r2RLineX.setMinimumSize(QtCore.QSize(70, 40))
        self.r2RLineX.setMaximumSize(QtCore.QSize(70, 16777215))
        self.r2RLineX.setObjectName("r2RLineX")
        self.horizontalLayout_3.addWidget(self.r2RLineX)
        spacerItem5 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.r2rBtnByCompare = QtWidgets.QPushButton(self.layoutWidget3)
        self.r2rBtnByCompare.setMinimumSize(QtCore.QSize(50, 30))
        self.r2rBtnByCompare.setMaximumSize(QtCore.QSize(0, 50))
        self.r2rBtnByCompare.setObjectName("r2rBtnByCompare")
        self.horizontalLayout_3.addWidget(self.r2rBtnByCompare)
        spacerItem6 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.r2rBtnByCompare_3 = QtWidgets.QPushButton(self.layoutWidget3)
        self.r2rBtnByCompare_3.setMinimumSize(QtCore.QSize(50, 30))
        self.r2rBtnByCompare_3.setMaximumSize(QtCore.QSize(0, 50))
        self.r2rBtnByCompare_3.setText("")
        self.r2rBtnByCompare_3.setObjectName("r2rBtnByCompare_3")
        self.horizontalLayout_3.addWidget(self.r2rBtnByCompare_3)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setMinimumSize(QtCore.QSize(1155, 62))
        self.groupBox_5.setMaximumSize(QtCore.QSize(1155, 62))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.r2rBtnOffset = QtWidgets.QPushButton(self.groupBox_5)
        self.r2rBtnOffset.setGeometry(QtCore.QRect(740, 10, 60, 45))
        self.r2rBtnOffset.setMinimumSize(QtCore.QSize(60, 45))
        self.r2rBtnOffset.setMaximumSize(QtCore.QSize(60, 45))
        self.r2rBtnOffset.setObjectName("r2rBtnOffset")
        self.r2rBtnOffset_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.r2rBtnOffset_2.setGeometry(QtCore.QRect(810, 10, 60, 45))
        self.r2rBtnOffset_2.setMinimumSize(QtCore.QSize(60, 45))
        self.r2rBtnOffset_2.setMaximumSize(QtCore.QSize(60, 45))
        self.r2rBtnOffset_2.setText("")
        self.r2rBtnOffset_2.setObjectName("r2rBtnOffset_2")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget4.setGeometry(QtCore.QRect(11, 11, 722, 42))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_7.setMinimumSize(QtCore.QSize(60, 0))
        self.label_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_8.setMinimumSize(QtCore.QSize(60, 0))
        self.label_8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_9.setMinimumSize(QtCore.QSize(60, 0))
        self.label_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_10.setMinimumSize(QtCore.QSize(60, 0))
        self.label_10.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_11.setMinimumSize(QtCore.QSize(60, 0))
        self.label_11.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_12.setMinimumSize(QtCore.QSize(60, 0))
        self.label_12.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_13.setMinimumSize(QtCore.QSize(60, 0))
        self.label_13.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 6, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_14.setMinimumSize(QtCore.QSize(60, 0))
        self.label_14.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 7, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_15.setMinimumSize(QtCore.QSize(60, 0))
        self.label_15.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 8, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_16.setMinimumSize(QtCore.QSize(60, 0))
        self.label_16.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 9, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_17.setMinimumSize(QtCore.QSize(60, 0))
        self.label_17.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 0, 10, 1, 1)
        self.doubleSpinTx = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.doubleSpinTx.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinTx.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinTx.setDecimals(3)
        self.doubleSpinTx.setMinimum(-0.2)
        self.doubleSpinTx.setMaximum(0.2)
        self.doubleSpinTx.setSingleStep(0.001)
        self.doubleSpinTx.setObjectName("doubleSpinTx")
        self.gridLayout_5.addWidget(self.doubleSpinTx, 1, 0, 1, 1)
        self.doubleSpinTy = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.doubleSpinTy.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinTy.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinTy.setDecimals(3)
        self.doubleSpinTy.setMinimum(-0.2)
        self.doubleSpinTy.setMaximum(0.2)
        self.doubleSpinTy.setSingleStep(0.001)
        self.doubleSpinTy.setObjectName("doubleSpinTy")
        self.gridLayout_5.addWidget(self.doubleSpinTy, 1, 1, 1, 1)
        self.doubleSpinEx = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.doubleSpinEx.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinEx.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinEx.setDecimals(1)
        self.doubleSpinEx.setMinimum(-1.0)
        self.doubleSpinEx.setMaximum(1.0)
        self.doubleSpinEx.setSingleStep(0.1)
        self.doubleSpinEx.setObjectName("doubleSpinEx")
        self.gridLayout_5.addWidget(self.doubleSpinEx, 1, 2, 1, 1)
        self.doubleSpinEy = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.doubleSpinEy.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinEy.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinEy.setDecimals(1)
        self.doubleSpinEy.setMinimum(-1.0)
        self.doubleSpinEy.setMaximum(1.0)
        self.doubleSpinEy.setSingleStep(0.1)
        self.doubleSpinEy.setObjectName("doubleSpinEy")
        self.gridLayout_5.addWidget(self.doubleSpinEy, 1, 3, 1, 1)
        self.doubleSpinOrt = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.doubleSpinOrt.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinOrt.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinOrt.setDecimals(1)
        self.doubleSpinOrt.setMinimum(-1.0)
        self.doubleSpinOrt.setMaximum(1.0)
        self.doubleSpinOrt.setSingleStep(0.1)
        self.doubleSpinOrt.setObjectName("doubleSpinOrt")
        self.gridLayout_5.addWidget(self.doubleSpinOrt, 1, 4, 1, 1)
        self.doubleSpinRot = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.doubleSpinRot.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinRot.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinRot.setDecimals(1)
        self.doubleSpinRot.setMinimum(-1.0)
        self.doubleSpinRot.setMaximum(1.0)
        self.doubleSpinRot.setSingleStep(0.1)
        self.doubleSpinRot.setObjectName("doubleSpinRot")
        self.gridLayout_5.addWidget(self.doubleSpinRot, 1, 5, 1, 1)
        self.doubleSpinBoxSMag = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.doubleSpinBoxSMag.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinBoxSMag.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinBoxSMag.setDecimals(1)
        self.doubleSpinBoxSMag.setMinimum(-5.0)
        self.doubleSpinBoxSMag.setMaximum(5.0)
        self.doubleSpinBoxSMag.setSingleStep(0.1)
        self.doubleSpinBoxSMag.setObjectName("doubleSpinBoxSMag")
        self.gridLayout_5.addWidget(self.doubleSpinBoxSMag, 1, 6, 1, 1)
        self.doubleSpinSRot = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.doubleSpinSRot.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinSRot.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinSRot.setDecimals(1)
        self.doubleSpinSRot.setMinimum(-5.0)
        self.doubleSpinSRot.setMaximum(5.0)
        self.doubleSpinSRot.setSingleStep(0.1)
        self.doubleSpinSRot.setObjectName("doubleSpinSRot")
        self.gridLayout_5.addWidget(self.doubleSpinSRot, 1, 7, 1, 1)
        self.doubleSpinAMag = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.doubleSpinAMag.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinAMag.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinAMag.setDecimals(1)
        self.doubleSpinAMag.setMinimum(-5.0)
        self.doubleSpinAMag.setMaximum(5.0)
        self.doubleSpinAMag.setSingleStep(0.1)
        self.doubleSpinAMag.setObjectName("doubleSpinAMag")
        self.gridLayout_5.addWidget(self.doubleSpinAMag, 1, 8, 1, 1)
        self.doubleSpinARot = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.doubleSpinARot.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinARot.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinARot.setDecimals(1)
        self.doubleSpinARot.setMinimum(-5.0)
        self.doubleSpinARot.setMaximum(5.0)
        self.doubleSpinARot.setSingleStep(0.1)
        self.doubleSpinARot.setObjectName("doubleSpinARot")
        self.gridLayout_5.addWidget(self.doubleSpinARot, 1, 9, 1, 1)
        self.doubleSpinCD = QtWidgets.QDoubleSpinBox(self.layoutWidget4)
        self.doubleSpinCD.setMinimumSize(QtCore.QSize(60, 0))
        self.doubleSpinCD.setMaximumSize(QtCore.QSize(60, 16777215))
        self.doubleSpinCD.setDecimals(1)
        self.doubleSpinCD.setSingleStep(0.1)
        self.doubleSpinCD.setObjectName("doubleSpinCD")
        self.gridLayout_5.addWidget(self.doubleSpinCD, 1, 10, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_5)
        self.r2rTab = QtWidgets.QTableWidget(self.tab_3)
        self.r2rTab.setMinimumSize(QtCore.QSize(0, 0))
        self.r2rTab.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.r2rTab.setObjectName("r2rTab")
        self.r2rTab.setColumnCount(0)
        self.r2rTab.setRowCount(0)
        self.verticalLayout.addWidget(self.r2rTab)
        self.scTable.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.partBtn1 = QtWidgets.QPushButton(self.tab_4)
        self.partBtn1.setObjectName("partBtn1")
        self.horizontalLayout_11.addWidget(self.partBtn1)
        self.partBtn2 = QtWidgets.QPushButton(self.tab_4)
        self.partBtn2.setObjectName("partBtn2")
        self.horizontalLayout_11.addWidget(self.partBtn2)
        spacerItem7 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.partLineEdit1 = QtWidgets.QLineEdit(self.tab_4)
        self.partLineEdit1.setObjectName("partLineEdit1")
        self.horizontalLayout_11.addWidget(self.partLineEdit1)
        self.partBtn3 = QtWidgets.QPushButton(self.tab_4)
        self.partBtn3.setObjectName("partBtn3")
        self.horizontalLayout_11.addWidget(self.partBtn3)
        spacerItem8 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.horizontalLayout_11.setStretch(5, 100)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.partTab = QtWidgets.QTableWidget(self.tab_4)
        self.partTab.setObjectName("partTab")
        self.partTab.setColumnCount(0)
        self.partTab.setRowCount(0)
        self.verticalLayout_8.addWidget(self.partTab)
        self.scTable.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_11.addWidget(self.label_5, 0, 0, 1, 1)
        self.idpButton1 = QtWidgets.QPushButton(self.tab_5)
        self.idpButton1.setMinimumSize(QtCore.QSize(105, 20))
        self.idpButton1.setMaximumSize(QtCore.QSize(105, 20))
        self.idpButton1.setObjectName("idpButton1")
        self.gridLayout_11.addWidget(self.idpButton1, 0, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem9, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_11.addWidget(self.label_6, 0, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setObjectName("label_18")
        self.gridLayout_11.addWidget(self.label_18, 0, 4, 1, 1)
        self.cdLineEdit1 = QtWidgets.QLineEdit(self.tab_5)
        self.cdLineEdit1.setObjectName("cdLineEdit1")
        self.gridLayout_11.addWidget(self.cdLineEdit1, 0, 5, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_6.setMinimumSize(QtCore.QSize(221, 0))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.cdRadio_2 = QtWidgets.QRadioButton(self.groupBox_6)
        self.cdRadio_2.setGeometry(QtCore.QRect(170, 1, 47, 19))
        self.cdRadio_2.setChecked(True)
        self.cdRadio_2.setObjectName("cdRadio_2")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(5, 1, 106, 16))
        self.label_19.setObjectName("label_19")
        self.cdRadio1 = QtWidgets.QRadioButton(self.groupBox_6)
        self.cdRadio1.setGeometry(QtCore.QRect(117, 1, 47, 19))
        self.cdRadio1.setObjectName("cdRadio1")
        self.gridLayout_11.addWidget(self.groupBox_6, 0, 6, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.tab_5)
        self.label_20.setObjectName("label_20")
        self.gridLayout_11.addWidget(self.label_20, 0, 8, 1, 1)
        self.cdLineEdit2 = QtWidgets.QLineEdit(self.tab_5)
        self.cdLineEdit2.setObjectName("cdLineEdit2")
        self.gridLayout_11.addWidget(self.cdLineEdit2, 0, 9, 1, 1)
        self.idpButton2 = QtWidgets.QPushButton(self.tab_5)
        self.idpButton2.setMinimumSize(QtCore.QSize(105, 20))
        self.idpButton2.setMaximumSize(QtCore.QSize(105, 20))
        self.idpButton2.setObjectName("idpButton2")
        self.gridLayout_11.addWidget(self.idpButton2, 0, 10, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_11.addWidget(self.label_37, 1, 0, 1, 1)
        self.idpButton1_3 = QtWidgets.QPushButton(self.tab_5)
        self.idpButton1_3.setMinimumSize(QtCore.QSize(105, 20))
        self.idpButton1_3.setMaximumSize(QtCore.QSize(105, 20))
        self.idpButton1_3.setObjectName("idpButton1_3")
        self.gridLayout_11.addWidget(self.idpButton1_3, 1, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(45, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem10, 1, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.gridLayout_11.addWidget(self.label_38, 1, 3, 1, 1)
        self.cdLab8_3 = QtWidgets.QLabel(self.tab_5)
        self.cdLab8_3.setAlignment(QtCore.Qt.AlignCenter)
        self.cdLab8_3.setObjectName("cdLab8_3")
        self.gridLayout_11.addWidget(self.cdLab8_3, 1, 4, 1, 1)
        self.cdLineEdit3_5 = QtWidgets.QLineEdit(self.tab_5)
        self.cdLineEdit3_5.setObjectName("cdLineEdit3_5")
        self.gridLayout_11.addWidget(self.cdLineEdit3_5, 1, 5, 1, 1)
        self.cdLab5_10 = QtWidgets.QLabel(self.tab_5)
        self.cdLab5_10.setObjectName("cdLab5_10")
        self.gridLayout_11.addWidget(self.cdLab5_10, 1, 6, 1, 1)
        self.cdLineEdit4_3 = QtWidgets.QLineEdit(self.tab_5)
        self.cdLineEdit4_3.setObjectName("cdLineEdit4_3")
        self.gridLayout_11.addWidget(self.cdLineEdit4_3, 1, 7, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_19.setMinimumSize(QtCore.QSize(210, 0))
        self.groupBox_19.setTitle("")
        self.groupBox_19.setObjectName("groupBox_19")
        self.cdRadio4 = QtWidgets.QRadioButton(self.groupBox_19)
        self.cdRadio4.setGeometry(QtCore.QRect(140, 1, 58, 19))
        self.cdRadio4.setObjectName("cdRadio4")
        self.cdLab5_11 = QtWidgets.QLabel(self.groupBox_19)
        self.cdLab5_11.setGeometry(QtCore.QRect(5, 1, 72, 16))
        self.cdLab5_11.setObjectName("cdLab5_11")
        self.cdRadio3 = QtWidgets.QRadioButton(self.groupBox_19)
        self.cdRadio3.setGeometry(QtCore.QRect(83, 1, 51, 19))
        self.cdRadio3.setObjectName("cdRadio3")
        self.gridLayout_11.addWidget(self.groupBox_19, 1, 8, 1, 2)
        self.updateButton = QtWidgets.QPushButton(self.tab_5)
        self.updateButton.setObjectName("updateButton")
        self.gridLayout_11.addWidget(self.updateButton, 1, 10, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout_11)
        spacerItem11 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.horizontalLayout_9.setStretch(1, 100)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_39 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.horizontalLayout_5.addWidget(self.label_39)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_13.setMinimumSize(QtCore.QSize(221, 0))
        self.groupBox_13.setTitle("")
        self.groupBox_13.setObjectName("groupBox_13")
        self.radioResult11 = QtWidgets.QRadioButton(self.groupBox_13)
        self.radioResult11.setGeometry(QtCore.QRect(108, 4, 47, 19))
        self.radioResult11.setObjectName("radioResult11")
        self.radioResult21 = QtWidgets.QRadioButton(self.groupBox_13)
        self.radioResult21.setGeometry(QtCore.QRect(170, 4, 47, 19))
        self.radioResult21.setObjectName("radioResult21")
        self.cdLab3_2 = QtWidgets.QLabel(self.groupBox_13)
        self.cdLab3_2.setGeometry(QtCore.QRect(7, 4, 81, 16))
        self.cdLab3_2.setObjectName("cdLab3_2")
        self.horizontalLayout_5.addWidget(self.groupBox_13)
        spacerItem12 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.label_41 = QtWidgets.QLabel(self.tab_5)
        self.label_41.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_5.addWidget(self.label_41)
        spacerItem13 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.updateButton_3 = QtWidgets.QPushButton(self.tab_5)
        self.updateButton_3.setObjectName("updateButton_3")
        self.horizontalLayout_5.addWidget(self.updateButton_3)
        spacerItem14 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        spacerItem15 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem15)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_5)
        self.updateButton_4 = QtWidgets.QPushButton(self.tab_5)
        self.updateButton_4.setObjectName("updateButton_4")
        self.horizontalLayout_10.addWidget(self.updateButton_4)
        spacerItem16 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem16)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_40 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_7.addWidget(self.label_40)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem17)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.cdTab = QtWidgets.QTableWidget(self.tab_5)
        self.cdTab.setObjectName("cdTab")
        self.cdTab.setColumnCount(0)
        self.cdTab.setRowCount(0)
        self.verticalLayout_7.addWidget(self.cdTab)
        self.scTable.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_10.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.ovlRadio1 = QtWidgets.QRadioButton(self.groupBox_10)
        self.ovlRadio1.setGeometry(QtCore.QRect(588, 5, 89, 17))
        self.ovlRadio1.setObjectName("ovlRadio1")
        self.ovlRadio2 = QtWidgets.QRadioButton(self.groupBox_10)
        self.ovlRadio2.setGeometry(QtCore.QRect(638, 5, 89, 17))
        self.ovlRadio2.setObjectName("ovlRadio2")
        self.ovlButton3 = QtWidgets.QPushButton(self.groupBox_10)
        self.ovlButton3.setGeometry(QtCore.QRect(849, 5, 105, 20))
        self.ovlButton3.setMinimumSize(QtCore.QSize(105, 20))
        self.ovlButton3.setMaximumSize(QtCore.QSize(105, 20))
        self.ovlButton3.setObjectName("ovlButton3")
        self.ovlLineEdit2_3 = QtWidgets.QLineEdit(self.groupBox_10)
        self.ovlLineEdit2_3.setGeometry(QtCore.QRect(698, 5, 141, 20))
        self.ovlLineEdit2_3.setAutoFillBackground(False)
        self.ovlLineEdit2_3.setObjectName("ovlLineEdit2_3")
        self.ovlButton2 = QtWidgets.QPushButton(self.groupBox_10)
        self.ovlButton2.setGeometry(QtCore.QRect(450, 5, 105, 20))
        self.ovlButton2.setMinimumSize(QtCore.QSize(105, 20))
        self.ovlButton2.setMaximumSize(QtCore.QSize(105, 20))
        self.ovlButton2.setObjectName("ovlButton2")
        self.ovlButton1 = QtWidgets.QPushButton(self.groupBox_10)
        self.ovlButton1.setGeometry(QtCore.QRect(5, 5, 105, 20))
        self.ovlButton1.setMinimumSize(QtCore.QSize(105, 20))
        self.ovlButton1.setMaximumSize(QtCore.QSize(105, 20))
        self.ovlButton1.setObjectName("ovlButton1")
        self.label_22 = QtWidgets.QLabel(self.groupBox_10)
        self.label_22.setGeometry(QtCore.QRect(283, 5, 28, 16))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_21 = QtWidgets.QLabel(self.groupBox_10)
        self.label_21.setGeometry(QtCore.QRect(116, 5, 28, 16))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.ovlLineEdit2 = QtWidgets.QLineEdit(self.groupBox_10)
        self.ovlLineEdit2.setGeometry(QtCore.QRect(317, 5, 127, 20))
        self.ovlLineEdit2.setObjectName("ovlLineEdit2")
        self.ovlLineEdit1 = QtWidgets.QLineEdit(self.groupBox_10)
        self.ovlLineEdit1.setGeometry(QtCore.QRect(150, 5, 127, 20))
        self.ovlLineEdit1.setObjectName("ovlLineEdit1")
        self.verticalLayout_2.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_11.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.ovlLineEdit4 = QtWidgets.QLineEdit(self.groupBox_11)
        self.ovlLineEdit4.setGeometry(QtCore.QRect(268, 5, 701, 20))
        self.ovlLineEdit4.setObjectName("ovlLineEdit4")
        self.ovlButton4 = QtWidgets.QPushButton(self.groupBox_11)
        self.ovlButton4.setGeometry(QtCore.QRect(1000, 5, 105, 20))
        self.ovlButton4.setMinimumSize(QtCore.QSize(105, 20))
        self.ovlButton4.setMaximumSize(QtCore.QSize(105, 20))
        self.ovlButton4.setObjectName("ovlButton4")
        self.ovlLineEdit3 = QtWidgets.QLineEdit(self.groupBox_11)
        self.ovlLineEdit3.setGeometry(QtCore.QRect(5, 5, 121, 20))
        self.ovlLineEdit3.setObjectName("ovlLineEdit3")
        self.ovlLineEdit5 = QtWidgets.QLineEdit(self.groupBox_11)
        self.ovlLineEdit5.setGeometry(QtCore.QRect(135, 5, 121, 20))
        self.ovlLineEdit5.setObjectName("ovlLineEdit5")
        self.verticalLayout_2.addWidget(self.groupBox_11)
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_21.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_21.setMaximumSize(QtCore.QSize(16777215, 30))
        self.groupBox_21.setTitle("")
        self.groupBox_21.setObjectName("groupBox_21")
        self.ovlButton4_2 = QtWidgets.QPushButton(self.groupBox_21)
        self.ovlButton4_2.setGeometry(QtCore.QRect(3, 5, 105, 20))
        self.ovlButton4_2.setMinimumSize(QtCore.QSize(105, 20))
        self.ovlButton4_2.setMaximumSize(QtCore.QSize(105, 20))
        self.ovlButton4_2.setObjectName("ovlButton4_2")
        self.ovlButton4_5 = QtWidgets.QPushButton(self.groupBox_21)
        self.ovlButton4_5.setGeometry(QtCore.QRect(113, 5, 105, 20))
        self.ovlButton4_5.setMinimumSize(QtCore.QSize(105, 20))
        self.ovlButton4_5.setMaximumSize(QtCore.QSize(105, 20))
        self.ovlButton4_5.setObjectName("ovlButton4_5")
        self.ovlButton4_6 = QtWidgets.QPushButton(self.groupBox_21)
        self.ovlButton4_6.setGeometry(QtCore.QRect(223, 5, 105, 20))
        self.ovlButton4_6.setMinimumSize(QtCore.QSize(105, 20))
        self.ovlButton4_6.setMaximumSize(QtCore.QSize(105, 20))
        self.ovlButton4_6.setObjectName("ovlButton4_6")
        self.verticalLayout_2.addWidget(self.groupBox_21)
        self.ovlTab = QtWidgets.QTableWidget(self.tab_6)
        self.ovlTab.setObjectName("ovlTab")
        self.ovlTab.setColumnCount(0)
        self.ovlTab.setRowCount(0)
        self.verticalLayout_2.addWidget(self.ovlTab)
        self.scTable.addTab(self.tab_6, "")
        self.verticalLayout_5.addWidget(self.scTable)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1239, 20))
        self.menubar.setMinimumSize(QtCore.QSize(0, 20))
        self.menubar.setObjectName("menubar")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        self.menuExit = QtWidgets.QMenu(self.menubar)
        self.menuExit.setObjectName("menuExit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 25))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionEX1 = QtWidgets.QAction(MainWindow)
        self.actionEX1.setObjectName("actionEX1")
        self.actionEX2 = QtWidgets.QAction(MainWindow)
        self.actionEX2.setObjectName("actionEX2")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuTool.addAction(self.actionEX1)
        self.menuTool.addAction(self.actionEX2)
        self.menuExit.addAction(self.actionExit)
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuExit.menuAction())

        self.retranslateUi(MainWindow)
        self.scTable.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "光刻日常使用"))
        self.label.setText(_translate("MainWindow", "开始"))
        self.label_2.setText(_translate("MainWindow", "结束"))
        self.exLabel.setText(_translate("MainWindow", "请输入产品名："))
        self.exLabel_2.setText(_translate("MainWindow", "请选择产品类型："))
        self.exRadioButton_3.setText(_translate("MainWindow", "旧产品"))
        self.exRadioButton_4.setText(_translate("MainWindow", "新产品"))
        self.exLabel_3.setText(_translate("MainWindow", "编程"))
        self.exPushButton.setText(_translate("MainWindow", "读取Excel数据表"))
        self.exPushButton_2.setText(_translate("MainWindow", "合并数据"))
        self.exLabel_4.setText(_translate("MainWindow", "检查"))
        self.exPushButton_3.setText(_translate("MainWindow", "检查ASML程序"))
        self.exPushButton_4.setText(_translate("MainWindow", "检查Nikon日期"))
        self.exLabel_23.setText(_translate("MainWindow", "INNER"))
        self.exPushButton_25.setText(_translate("MainWindow", "计算"))
        self.exPushButton_26.setText(_translate("MainWindow", "画图"))
        self.exPushButton_27.setText(_translate("MainWindow", "管芯"))
        self.exPushButton_10.setText(_translate("MainWindow", "插入"))
        self.exLabel_7.setText(_translate("MainWindow", "TrackRecipe"))
        self.exLabel_5.setText(_translate("MainWindow", "FullTech"))
        self.exLabel_8.setText(_translate("MainWindow", "INNER"))
        self.exLabel_6.setText(_translate("MainWindow", "Layer"))
        self.exPushButton_88.setText(_translate("MainWindow", "查询"))
        self.exLabel_9.setText(_translate("MainWindow", "NA"))
        self.exLabel_10.setText(_translate("MainWindow", "OUTER"))
        self.exPushButton_28.setText(_translate("MainWindow", "大视场"))
        self.exPushButton_29.setText(_translate("MainWindow", "普通非大视场"))
        self.exPushButton_30.setText(_translate("MainWindow", "SplitGate"))
        self.exPushButton_31.setText(_translate("MainWindow", "MPW"))
        self.scTable.setTabText(self.scTable.indexOf(self.tab), _translate("MainWindow", "曝光编程"))
        self.scBtn01.setText(_translate("MainWindow", "ESF限制"))
        self.scBtn02.setText(_translate("MainWindow", "量测SPC"))
        self.scBtn03.setText(_translate("MainWindow", "产品套刻"))
        self.scBtn04.setText(_translate("MainWindow", "套刻QC"))
        self.scBtn05.setText(_translate("MainWindow", "条宽QC"))
        self.scBtn06.setText(_translate("MainWindow", "YMS"))
        self.scBtn07.setText(_translate("MainWindow", "周返工"))
        self.scBtn08.setText(_translate("MainWindow", "预对位"))
        self.scBtn09.setText(_translate("MainWindow", "MCC"))
        self.scBtn10.setText(_translate("MainWindow", "Nikon调节"))
        self.scBtn11.setText(_translate("MainWindow", "备份表"))
        self.scBtn30.setText(_translate("MainWindow", "Excel"))
        self.scBtn31.setText(_translate("MainWindow", "CD UPDATE"))
        self.scBtn32.setText(_translate("MainWindow", "OVL UPDATE"))
        self.scBtn33.setText(_translate("MainWindow", "NIK VECTOR"))
        self.scBtn34.setText(_translate("MainWindow", "NIK DATE"))
        self.scBtn35.setText(_translate("MainWindow", "ASM BATCH"))
        self.scBtn36.setText(_translate("MainWindow", "ASM PRE"))
        self.scBtn37.setText(_translate("MainWindow", "PPCS ADO"))
        self.scBtn38.setText(_translate("MainWindow", "OVL OPT"))
        self.scBtn39.setText(_translate("MainWindow", "CDU CD"))
        self.scBtn40.setText(_translate("MainWindow", "CDU IMAGE"))
        self.scBtn41.setText(_translate("MainWindow", "ASM AWE"))
        self.scBtn51.setText(_translate("MainWindow", "RESERVED"))
        self.scBtn47.setText(_translate("MainWindow", "NIK FTP"))
        self.scBtn44.setText(_translate("MainWindow", "SPC99"))
        self.scBtn49.setText(_translate("MainWindow", "RESERVED"))
        self.scBtn43.setText(_translate("MainWindow", "ESF"))
        self.scBtn42.setText(_translate("MainWindow", "NIK ADJUST"))
        self.scBtn48.setText(_translate("MainWindow", "CDU OVL QC"))
        self.scBtn46.setText(_translate("MainWindow", "111 CD"))
        self.scBtn45.setText(_translate("MainWindow", "111 ASM"))
        self.scBtn50.setText(_translate("MainWindow", "RESERVED"))
        self.scTable.setTabText(self.scTable.indexOf(self.tab_2), _translate("MainWindow", "快捷路径"))
        self.r2rRadioBtn01.setText(_translate("MainWindow", "CD"))
        self.r2rRadioBtn02.setText(_translate("MainWindow", "OVL"))
        self.r2rBtn01.setText(_translate("MainWindow", "30天"))
        self.r2rBtn02.setText(_translate("MainWindow", "60天"))
        self.r2rBtn03.setText(_translate("MainWindow", "90天"))
        self.r2rBtn04.setText(_translate("MainWindow", "自选"))
        self.r2rBtnFilter.setText(_translate("MainWindow", "RESET"))
        self.r2rBtnByDate.setText(_translate("MainWindow", "ByDate"))
        self.r2rBtnByTool.setText(_translate("MainWindow", "ByTool"))
        self.r2rBtnByPart.setText(_translate("MainWindow", "ByPart"))
        self.r2rRadioTranX.setText(_translate("MainWindow", "TranX"))
        self.r2rRadioTranY.setText(_translate("MainWindow", "TranY"))
        self.r2rRadioExpX.setText(_translate("MainWindow", "ExpX"))
        self.r2rRadioExpY.setText(_translate("MainWindow", "ExpY"))
        self.r2rRadioOrt.setText(_translate("MainWindow", "Ort"))
        self.r2rRadioRot.setText(_translate("MainWindow", "Rot"))
        self.r2rRadioSMag.setText(_translate("MainWindow", "SMag"))
        self.r2rRadioSRot.setText(_translate("MainWindow", "SRot"))
        self.r2rRadioAMag.setText(_translate("MainWindow", "AMag"))
        self.r2rRadioARot.setText(_translate("MainWindow", "ARot"))
        self.r2rRadioCD.setText(_translate("MainWindow", "CD"))
        self.r2rBtnByCompare.setText(_translate("MainWindow", "前层"))
        self.r2rBtnOffset.setText(_translate("MainWindow", "OFFSET"))
        self.label_7.setText(_translate("MainWindow", "TranX"))
        self.label_8.setText(_translate("MainWindow", "TranY"))
        self.label_9.setText(_translate("MainWindow", "ExpX"))
        self.label_10.setText(_translate("MainWindow", "ExpY"))
        self.label_11.setText(_translate("MainWindow", "Ort"))
        self.label_12.setText(_translate("MainWindow", "Rot"))
        self.label_13.setText(_translate("MainWindow", "SMag"))
        self.label_14.setText(_translate("MainWindow", "SRot"))
        self.label_15.setText(_translate("MainWindow", "AMag"))
        self.label_16.setText(_translate("MainWindow", "ARot"))
        self.label_17.setText(_translate("MainWindow", "CD"))
        self.scTable.setTabText(self.scTable.indexOf(self.tab_3), _translate("MainWindow", "R2R"))
        self.partBtn1.setText(_translate("MainWindow", "产品清单"))
        self.partBtn2.setText(_translate("MainWindow", "汇总数据"))
        self.partBtn3.setText(_translate("MainWindow", "ByPart"))
        self.scTable.setTabText(self.scTable.indexOf(self.tab_4), _translate("MainWindow", "PART"))
        self.label_5.setText(_translate("MainWindow", "查询："))
        self.idpButton1.setText(_translate("MainWindow", "报错IDP查询"))
        self.label_6.setText(_translate("MainWindow", "更新："))
        self.label_18.setText(_translate("MainWindow", "请选择ID"))
        self.cdRadio_2.setText(_translate("MainWindow", "错误"))
        self.label_19.setText(_translate("MainWindow", "请输入Conclusion"))
        self.cdRadio1.setText(_translate("MainWindow", "正确"))
        self.label_20.setText(_translate("MainWindow", "请输入工号"))
        self.idpButton2.setText(_translate("MainWindow", "IDP结论更新"))
        self.label_37.setText(_translate("MainWindow", "查询："))
        self.idpButton1_3.setText(_translate("MainWindow", "报错AMP查询"))
        self.label_38.setText(_translate("MainWindow", "更新："))
        self.cdLab8_3.setText(_translate("MainWindow", "请选择ID"))
        self.cdLab5_10.setText(_translate("MainWindow", "更新工艺代码"))
        self.cdRadio4.setText(_translate("MainWindow", "Space"))
        self.cdLab5_11.setText(_translate("MainWindow", "更新条宽类型"))
        self.cdRadio3.setText(_translate("MainWindow", "Line"))
        self.updateButton.setText(_translate("MainWindow", "人工检查"))
        self.label_39.setText(_translate("MainWindow", "AMP反馈："))
        self.radioResult11.setText(_translate("MainWindow", "错误"))
        self.radioResult21.setText(_translate("MainWindow", "正确"))
        self.cdLab3_2.setText(_translate("MainWindow", "检查结果确认"))
        self.label_41.setText(_translate("MainWindow", "确认结果并反馈，默认设备端程序已处置！！"))
        self.updateButton_3.setText(_translate("MainWindow", "反馈更新"))
        self.updateButton_4.setText(_translate("MainWindow", "All_In_One"))
        self.label_40.setText(_translate("MainWindow", "object_1:space,0:line,20:inner_diameter          meas_kind_0:single,1:multipoint,2:radial          measurement_0:width,3:diameter\n"
"output_data_1:mean\',7:diameter(meas_kind设置为1,2时，该参数有效）                                     method_0:linear,1:threshold   "))
        self.scTable.setTabText(self.scTable.indexOf(self.tab_5), _translate("MainWindow", "CD"))
        self.ovlRadio1.setText(_translate("MainWindow", "正确"))
        self.ovlRadio2.setText(_translate("MainWindow", "错误"))
        self.ovlButton3.setText(_translate("MainWindow", "更新结论"))
        self.ovlButton2.setText(_translate("MainWindow", "自选查询"))
        self.ovlButton1.setText(_translate("MainWindow", "报错查询"))
        self.label_22.setText(_translate("MainWindow", "PPID"))
        self.label_21.setText(_translate("MainWindow", "PART"))
        self.ovlButton4.setText(_translate("MainWindow", "输入标准坐标"))
        self.ovlButton4_2.setText(_translate("MainWindow", "待下载"))
        self.ovlButton4_5.setText(_translate("MainWindow", "负值查询"))
        self.ovlButton4_6.setText(_translate("MainWindow", "坐标重叠"))
        self.scTable.setTabText(self.scTable.indexOf(self.tab_6), _translate("MainWindow", "OVL"))
        self.menuTool.setTitle(_translate("MainWindow", "编程"))
        self.menuExit.setTitle(_translate("MainWindow", "Exit"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionEX1.setText(_translate("MainWindow", "保存编程EXCEL"))
        self.actionEX2.setText(_translate("MainWindow", "查看坐标文件"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

