//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace EX7_34 {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DataSet1 : DataSet {
        
        private testDataTable tabletest;
        
        public DataSet1() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DataSet1(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["test"] != null)) {
                    this.Tables.Add(new testDataTable(ds.Tables["test"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public testDataTable test {
            get {
                return this.tabletest;
            }
        }
        
        public override DataSet Clone() {
            DataSet1 cln = ((DataSet1)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["test"] != null)) {
                this.Tables.Add(new testDataTable(ds.Tables["test"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tabletest = ((testDataTable)(this.Tables["test"]));
            if ((this.tabletest != null)) {
                this.tabletest.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "DataSet1";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DataSet1.xsd";
            this.Locale = new System.Globalization.CultureInfo("zh-CN");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tabletest = new testDataTable();
            this.Tables.Add(this.tabletest);
        }
        
        private bool ShouldSerializetest() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void testRowChangeEventHandler(object sender, testRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class testDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnid;
            
            private DataColumn column民族;
            
            private DataColumn column姓名;
            
            internal testDataTable() : 
                    base("test") {
                this.InitClass();
            }
            
            internal testDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn idColumn {
                get {
                    return this.columnid;
                }
            }
            
            internal DataColumn 民族Column {
                get {
                    return this.column民族;
                }
            }
            
            internal DataColumn 姓名Column {
                get {
                    return this.column姓名;
                }
            }
            
            public testRow this[int index] {
                get {
                    return ((testRow)(this.Rows[index]));
                }
            }
            
            public event testRowChangeEventHandler testRowChanged;
            
            public event testRowChangeEventHandler testRowChanging;
            
            public event testRowChangeEventHandler testRowDeleted;
            
            public event testRowChangeEventHandler testRowDeleting;
            
            public void AddtestRow(testRow row) {
                this.Rows.Add(row);
            }
            
            public testRow AddtestRow(string 民族, string 姓名) {
                testRow rowtestRow = ((testRow)(this.NewRow()));
                rowtestRow.ItemArray = new object[] {
                        null,
                        民族,
                        姓名};
                this.Rows.Add(rowtestRow);
                return rowtestRow;
            }
            
            public testRow FindByid(int id) {
                return ((testRow)(this.Rows.Find(new object[] {
                            id})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                testDataTable cln = ((testDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new testDataTable();
            }
            
            internal void InitVars() {
                this.columnid = this.Columns["id"];
                this.column民族 = this.Columns["民族"];
                this.column姓名 = this.Columns["姓名"];
            }
            
            private void InitClass() {
                this.columnid = new DataColumn("id", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnid);
                this.column民族 = new DataColumn("民族", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column民族);
                this.column姓名 = new DataColumn("姓名", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.column姓名);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnid}, true));
                this.columnid.AutoIncrement = true;
                this.columnid.AllowDBNull = false;
                this.columnid.ReadOnly = true;
                this.columnid.Unique = true;
            }
            
            public testRow NewtestRow() {
                return ((testRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new testRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(testRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.testRowChanged != null)) {
                    this.testRowChanged(this, new testRowChangeEvent(((testRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.testRowChanging != null)) {
                    this.testRowChanging(this, new testRowChangeEvent(((testRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.testRowDeleted != null)) {
                    this.testRowDeleted(this, new testRowChangeEvent(((testRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.testRowDeleting != null)) {
                    this.testRowDeleting(this, new testRowChangeEvent(((testRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovetestRow(testRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class testRow : DataRow {
            
            private testDataTable tabletest;
            
            internal testRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tabletest = ((testDataTable)(this.Table));
            }
            
            public int id {
                get {
                    return ((int)(this[this.tabletest.idColumn]));
                }
                set {
                    this[this.tabletest.idColumn] = value;
                }
            }
            
            public string 民族 {
                get {
                    try {
                        return ((string)(this[this.tabletest.民族Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tabletest.民族Column] = value;
                }
            }
            
            public string 姓名 {
                get {
                    try {
                        return ((string)(this[this.tabletest.姓名Column]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tabletest.姓名Column] = value;
                }
            }
            
            public bool Is民族Null() {
                return this.IsNull(this.tabletest.民族Column);
            }
            
            public void Set民族Null() {
                this[this.tabletest.民族Column] = System.Convert.DBNull;
            }
            
            public bool Is姓名Null() {
                return this.IsNull(this.tabletest.姓名Column);
            }
            
            public void Set姓名Null() {
                this[this.tabletest.姓名Column] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class testRowChangeEvent : EventArgs {
            
            private testRow eventRow;
            
            private DataRowAction eventAction;
            
            public testRowChangeEvent(testRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public testRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
