//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DataBase4 {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DataSet1 : DataSet {
        
        private bookDataTable tablebook;
        
        private userDataTable tableuser;
        
        private DataRelation relationuserbook;
        
        public DataSet1() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected DataSet1(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["book"] != null)) {
                    this.Tables.Add(new bookDataTable(ds.Tables["book"]));
                }
                if ((ds.Tables["user"] != null)) {
                    this.Tables.Add(new userDataTable(ds.Tables["user"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public bookDataTable book {
            get {
                return this.tablebook;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public userDataTable user {
            get {
                return this.tableuser;
            }
        }
        
        public override DataSet Clone() {
            DataSet1 cln = ((DataSet1)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["book"] != null)) {
                this.Tables.Add(new bookDataTable(ds.Tables["book"]));
            }
            if ((ds.Tables["user"] != null)) {
                this.Tables.Add(new userDataTable(ds.Tables["user"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tablebook = ((bookDataTable)(this.Tables["book"]));
            if ((this.tablebook != null)) {
                this.tablebook.InitVars();
            }
            this.tableuser = ((userDataTable)(this.Tables["user"]));
            if ((this.tableuser != null)) {
                this.tableuser.InitVars();
            }
            this.relationuserbook = this.Relations["userbook"];
        }
        
        private void InitClass() {
            this.DataSetName = "DataSet1";
            this.Prefix = "";
            this.Namespace = "http://www.tempuri.org/DataSet1.xsd";
            this.Locale = new System.Globalization.CultureInfo("zh-CN");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tablebook = new bookDataTable();
            this.Tables.Add(this.tablebook);
            this.tableuser = new userDataTable();
            this.Tables.Add(this.tableuser);
            ForeignKeyConstraint fkc;
            fkc = new ForeignKeyConstraint("userbook", new DataColumn[] {
                        this.tableuser.usernameColumn}, new DataColumn[] {
                        this.tablebook.usernameColumn});
            this.tablebook.Constraints.Add(fkc);
            fkc.AcceptRejectRule = AcceptRejectRule.None;
            fkc.DeleteRule = Rule.Cascade;
            fkc.UpdateRule = Rule.Cascade;
            this.relationuserbook = new DataRelation("userbook", new DataColumn[] {
                        this.tableuser.usernameColumn}, new DataColumn[] {
                        this.tablebook.usernameColumn}, false);
            this.Relations.Add(this.relationuserbook);
        }
        
        private bool ShouldSerializebook() {
            return false;
        }
        
        private bool ShouldSerializeuser() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void bookRowChangeEventHandler(object sender, bookRowChangeEvent e);
        
        public delegate void userRowChangeEventHandler(object sender, userRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class bookDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnusername;
            
            private DataColumn columnbookname;
            
            private DataColumn columndescription;
            
            internal bookDataTable() : 
                    base("book") {
                this.InitClass();
            }
            
            internal bookDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn usernameColumn {
                get {
                    return this.columnusername;
                }
            }
            
            internal DataColumn booknameColumn {
                get {
                    return this.columnbookname;
                }
            }
            
            internal DataColumn descriptionColumn {
                get {
                    return this.columndescription;
                }
            }
            
            public bookRow this[int index] {
                get {
                    return ((bookRow)(this.Rows[index]));
                }
            }
            
            public event bookRowChangeEventHandler bookRowChanged;
            
            public event bookRowChangeEventHandler bookRowChanging;
            
            public event bookRowChangeEventHandler bookRowDeleted;
            
            public event bookRowChangeEventHandler bookRowDeleting;
            
            public void AddbookRow(bookRow row) {
                this.Rows.Add(row);
            }
            
            public bookRow AddbookRow(userRow parentuserRowByuserbook, string bookname, string description) {
                bookRow rowbookRow = ((bookRow)(this.NewRow()));
                rowbookRow.ItemArray = new object[] {
                        parentuserRowByuserbook[0],
                        bookname,
                        description};
                this.Rows.Add(rowbookRow);
                return rowbookRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                bookDataTable cln = ((bookDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new bookDataTable();
            }
            
            internal void InitVars() {
                this.columnusername = this.Columns["username"];
                this.columnbookname = this.Columns["bookname"];
                this.columndescription = this.Columns["description"];
            }
            
            private void InitClass() {
                this.columnusername = new DataColumn("username", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnusername);
                this.columnbookname = new DataColumn("bookname", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnbookname);
                this.columndescription = new DataColumn("description", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columndescription);
            }
            
            public bookRow NewbookRow() {
                return ((bookRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new bookRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(bookRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.bookRowChanged != null)) {
                    this.bookRowChanged(this, new bookRowChangeEvent(((bookRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.bookRowChanging != null)) {
                    this.bookRowChanging(this, new bookRowChangeEvent(((bookRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.bookRowDeleted != null)) {
                    this.bookRowDeleted(this, new bookRowChangeEvent(((bookRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.bookRowDeleting != null)) {
                    this.bookRowDeleting(this, new bookRowChangeEvent(((bookRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovebookRow(bookRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class bookRow : DataRow {
            
            private bookDataTable tablebook;
            
            internal bookRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tablebook = ((bookDataTable)(this.Table));
            }
            
            public string username {
                get {
                    try {
                        return ((string)(this[this.tablebook.usernameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tablebook.usernameColumn] = value;
                }
            }
            
            public string bookname {
                get {
                    try {
                        return ((string)(this[this.tablebook.booknameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tablebook.booknameColumn] = value;
                }
            }
            
            public string description {
                get {
                    try {
                        return ((string)(this[this.tablebook.descriptionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tablebook.descriptionColumn] = value;
                }
            }
            
            public userRow userRow {
                get {
                    return ((userRow)(this.GetParentRow(this.Table.ParentRelations["userbook"])));
                }
                set {
                    this.SetParentRow(value, this.Table.ParentRelations["userbook"]);
                }
            }
            
            public bool IsusernameNull() {
                return this.IsNull(this.tablebook.usernameColumn);
            }
            
            public void SetusernameNull() {
                this[this.tablebook.usernameColumn] = System.Convert.DBNull;
            }
            
            public bool IsbooknameNull() {
                return this.IsNull(this.tablebook.booknameColumn);
            }
            
            public void SetbooknameNull() {
                this[this.tablebook.booknameColumn] = System.Convert.DBNull;
            }
            
            public bool IsdescriptionNull() {
                return this.IsNull(this.tablebook.descriptionColumn);
            }
            
            public void SetdescriptionNull() {
                this[this.tablebook.descriptionColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class bookRowChangeEvent : EventArgs {
            
            private bookRow eventRow;
            
            private DataRowAction eventAction;
            
            public bookRowChangeEvent(bookRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public bookRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class userDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnusername;
            
            private DataColumn columnEmail;
            
            private DataColumn columnaddress;
            
            internal userDataTable() : 
                    base("user") {
                this.InitClass();
            }
            
            internal userDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn usernameColumn {
                get {
                    return this.columnusername;
                }
            }
            
            internal DataColumn EmailColumn {
                get {
                    return this.columnEmail;
                }
            }
            
            internal DataColumn addressColumn {
                get {
                    return this.columnaddress;
                }
            }
            
            public userRow this[int index] {
                get {
                    return ((userRow)(this.Rows[index]));
                }
            }
            
            public event userRowChangeEventHandler userRowChanged;
            
            public event userRowChangeEventHandler userRowChanging;
            
            public event userRowChangeEventHandler userRowDeleted;
            
            public event userRowChangeEventHandler userRowDeleting;
            
            public void AdduserRow(userRow row) {
                this.Rows.Add(row);
            }
            
            public userRow AdduserRow(string username, string Email, string address) {
                userRow rowuserRow = ((userRow)(this.NewRow()));
                rowuserRow.ItemArray = new object[] {
                        username,
                        Email,
                        address};
                this.Rows.Add(rowuserRow);
                return rowuserRow;
            }
            
            public userRow FindByusername(string username) {
                return ((userRow)(this.Rows.Find(new object[] {
                            username})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                userDataTable cln = ((userDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new userDataTable();
            }
            
            internal void InitVars() {
                this.columnusername = this.Columns["username"];
                this.columnEmail = this.Columns["Email"];
                this.columnaddress = this.Columns["address"];
            }
            
            private void InitClass() {
                this.columnusername = new DataColumn("username", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnusername);
                this.columnEmail = new DataColumn("Email", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnEmail);
                this.columnaddress = new DataColumn("address", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnaddress);
                this.Constraints.Add(new UniqueConstraint("Constraint1", new DataColumn[] {
                                this.columnusername}, true));
                this.columnusername.AllowDBNull = false;
                this.columnusername.Unique = true;
            }
            
            public userRow NewuserRow() {
                return ((userRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new userRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(userRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.userRowChanged != null)) {
                    this.userRowChanged(this, new userRowChangeEvent(((userRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.userRowChanging != null)) {
                    this.userRowChanging(this, new userRowChangeEvent(((userRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.userRowDeleted != null)) {
                    this.userRowDeleted(this, new userRowChangeEvent(((userRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.userRowDeleting != null)) {
                    this.userRowDeleting(this, new userRowChangeEvent(((userRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveuserRow(userRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class userRow : DataRow {
            
            private userDataTable tableuser;
            
            internal userRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tableuser = ((userDataTable)(this.Table));
            }
            
            public string username {
                get {
                    return ((string)(this[this.tableuser.usernameColumn]));
                }
                set {
                    this[this.tableuser.usernameColumn] = value;
                }
            }
            
            public string Email {
                get {
                    try {
                        return ((string)(this[this.tableuser.EmailColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableuser.EmailColumn] = value;
                }
            }
            
            public string address {
                get {
                    try {
                        return ((string)(this[this.tableuser.addressColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("无法获取值，因为它是 DBNull。", e);
                    }
                }
                set {
                    this[this.tableuser.addressColumn] = value;
                }
            }
            
            public bool IsEmailNull() {
                return this.IsNull(this.tableuser.EmailColumn);
            }
            
            public void SetEmailNull() {
                this[this.tableuser.EmailColumn] = System.Convert.DBNull;
            }
            
            public bool IsaddressNull() {
                return this.IsNull(this.tableuser.addressColumn);
            }
            
            public void SetaddressNull() {
                this[this.tableuser.addressColumn] = System.Convert.DBNull;
            }
            
            public bookRow[] GetbookRows() {
                return ((bookRow[])(this.GetChildRows(this.Table.ChildRelations["userbook"])));
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class userRowChangeEvent : EventArgs {
            
            private userRow eventRow;
            
            private DataRowAction eventAction;
            
            public userRowChangeEvent(userRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public userRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
